---
title: "p8105_hw6_yx2507"
author: "Yuqing Xue"
date: "11/22/2019"
output: github_document
---

```{r setup, message=FALSE}
library(tidyverse)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
set.seed(1)
```


# problem 1

## load and clean the data
```{r}
bw_df=read_csv(file = "./data/birthweight.csv")%>%
  janitor::clean_names()%>%
  mutate(
    babysex = fct_infreq(as.factor(babysex)),
    frace = fct_infreq(as.factor(frace)),
    malform = fct_infreq(as.factor(malform)),
    mrace = fct_infreq(as.factor(mrace))
  )

# check missing data
missing= bw_df %>%
   summarise_all((funs(sum(is.na(.))))) 
missing
```

after cleaning the data, we check the missing data and make sure that there is no missing data.
